### ISSUE TITLE
首頁輪播區塊，連續點左/右按鈕，輪播項目會不見

### ISSUE THREAD

**Issue by hsinny** [Hsinny/lunar-landing-page#4]
實際運用輪播區塊，連續點左/右按鈕，輪播項目會不見
- 這邊輪播要不要統一用 embla-carousel，它的 Demo 看起來應該是可以做到我們需要的效果？
https://www.embla-carousel.com/examples/static/#align

輪播當前在最左邊時，限制不能往左滑參考：
```
 const handlePrevScroll = () => {
    if (scrollWidth >= 0) return;
}
```

_Originally posted by @Hsinny in https://github.com/Hsinny/lunar-landing-page/pull/3#discussion_r1199599691_

**Comment by shujhen** [comment]
fixed in #10
